[package]
name = "indexer-attestation"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow.workspace = true
indexer-allocation = { path = "../allocation" }
thegraph-core.workspace = true


[dev-dependencies]
test-assets = { path = "../test-assets" }
test-log.workspace = true
