[indexer]
indexer_address = "INDEXER_ADDRESS_PLACEHOLDER"
operator_mnemonic = "INDEXER_MNEMONIC_PLACEHOLDER"

[database]
postgres_url = "postgresql://postgres@postgres:POSTGRES_PORT_PLACEHOLDER/indexer_components_1"

[graph_node]
query_url = "http://graph-node:GRAPH_NODE_GRAPHQL_PORT_PLACEHOLDER"
status_url = "http://graph-node:GRAPH_NODE_STATUS_PORT_PLACEHOLDER/graphql"

[subgraphs.network]
query_url = "http://graph-node:GRAPH_NODE_GRAPHQL_PORT_PLACEHOLDER/subgraphs/name/graph-network"
recently_closed_allocation_buffer_secs = 60
syncing_interval_secs = 30

[subgraphs.escrow]
query_url = "http://graph-node:GRAPH_NODE_GRAPHQL_PORT_PLACEHOLDER/subgraphs/name/semiotic/tap"
syncing_interval_secs = 30

[blockchain]
chain_id = 1337
receipts_verifier_address = "VERIFIER_ADDRESS_PLACEHOLDER"

[service]
host_and_port = "0.0.0.0:INDEXER_SERVICE_PORT_PLACEHOLDER"
url_prefix = "/"
serve_network_subgraph = false
serve_escrow_subgraph = false

[tap]
max_amount_willing_to_lose_grt = 1000

[tap.rav_request]
timestamp_buffer_secs = 1000

[tap.sender_aggregator_endpoints]
"ACCOUNT0_ADDRESS_PLACEHOLDER" = "http://tap-aggregator:TAP_AGGREGATOR_PORT_PLACEHOLDER"
