[indexer]
indexer_address = "INDEXER_ADDRESS_PLACEHOLDER"
operator_mnemonic = "INDEXER_MNEMONIC_PLACEHOLDER"

[database]
postgres_url = "postgres://postgres@postgres:POSTGRES_PORT_PLACEHOLDER/indexer_components_1"

[graph_node]
query_url = "http://graph-node:8000"
status_url = "http://graph-node:8030/graphql"

[subgraphs.network]
query_url = "http://graph-node:8000/subgraphs/name/graph-network"
deployment_id = "NETWORK_DEPLOYMENT_PLACEHOLDER"
syncing_interval_secs = 5
recently_closed_allocation_buffer_secs = 10

[subgraphs.escrow]
query_url = "http://graph-node:8000/subgraphs/name/semiotic/tap"
deployment_id = "ESCROW_DEPLOYMENT_PLACEHOLDER"
syncing_interval_secs = 5

# Note: V2 escrow accounts are in the network subgraph, not a separate TAP v2 subgraph

[blockchain]
chain_id = 1337
receipts_verifier_address = "VERIFIER_ADDRESS_PLACEHOLDER"

[service]
host_and_port = "0.0.0.0:7601"
free_query_auth_token = "freestuff"

[service.tap]
max_receipt_value_grt = "0.001"

[tap]
max_amount_willing_to_lose_grt = 1000

[tap.rav_request]
# Set a lower timestamp buffer threshold
timestamp_buffer_secs = 30
# The trigger value divisor is used to calculate the trigger value for the RAV request.
# using the formula:
# trigger_value = max_amount_willing_to_lose_grt / trigger_value_divisor
# where the default value for max_amount_willing_to_lose_grt is 1000
# the idea to set this for trigger_value to be 0.002
# requiring the sender to send at least 20 receipts of 0.0001 grt
trigger_value_divisor = 500_000

[tap.sender_aggregator_endpoints]
"ACCOUNT0_ADDRESS_PLACEHOLDER" = "http://tap-aggregator:7610"

[horizon]
# Horizon migration mode: legacy | transition | full
# - legacy: Only v1 TAP receipts supported (pre-migration)
# - transition: Both v1 and v2 TAP receipts supported (during migration)  
# - full: Only v2 TAP receipts supported (post-migration)
mode = "transition"
