//! Gateway DIPS protocol types (auto-generated).
//!
//! These types define the Gateway-to-Dipper interface. Not used by indexer-rs
//! but included for completeness as both services share the same proto package.

// This file is @generated by prost-build.
pub mod graphprotocol {
    pub mod gateway {
        pub mod dips {
            include!("graphprotocol.gateway.dips.rs");
        }
    }
}
