// This file is @generated by prost-build.
/// *
///
/// A request to propose a new *indexing agreement* to an *indexer*.
///
/// See the `DipsService.SubmitAgreementProposal` method.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SubmitAgreementProposalRequest {
    #[prost(uint64, tag = "1")]
    pub version: u64,
    /// / ABI-encoded SignedRCA (RecurringCollectionAgreement plus signature).
    #[prost(bytes = "vec", tag = "2")]
    pub signed_rca: ::prost::alloc::vec::Vec<u8>,
}
/// *
///
/// A response to a request to propose a new *indexing agreement* to an *indexer*.
///
/// The outcome is either `accepted` or `rejected` -- exactly one is set. A
/// rejection carries a `RejectReason` plus an optional free-text detail.
///
/// See the `DipsService.SubmitAgreementProposal` method.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SubmitAgreementProposalResponse {
    #[prost(oneof = "submit_agreement_proposal_response::Outcome", tags = "1, 2")]
    pub outcome: ::core::option::Option<submit_agreement_proposal_response::Outcome>,
}
/// Nested message and enum types in `SubmitAgreementProposalResponse`.
pub mod submit_agreement_proposal_response {
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Outcome {
        /// / Set when the proposal was accepted.
        #[prost(message, tag = "1")]
        Accepted(super::Accepted),
        /// / Set when the proposal was rejected.
        #[prost(message, tag = "2")]
        Rejected(super::Rejected),
    }
}
/// *
///
/// An accepted *indexing agreement* proposal. Empty for now; accept-only fields
/// can be added later without disturbing the reject path.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Accepted {}
/// *
///
/// A rejected *indexing agreement* proposal.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Rejected {
    /// / Why the proposal was rejected.
    #[prost(enumeration = "RejectReason", tag = "1")]
    pub reason: i32,
    /// / Optional human-readable detail; may be empty.
    #[prost(string, tag = "2")]
    pub detail: ::prost::alloc::string::String,
}
/// *
///
/// The reason an *indexer* rejected an *indexing agreement* proposal. Values may
/// be added over time; an older reader should treat an unrecognised reason as
/// UNSPECIFIED (the catch-all).
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum RejectReason {
    /// / Rejected for a reason not covered below (the catch-all).
    Unspecified = 0,
    /// / The offered price is below the indexer's minimum.
    PriceTooLow = 1,
    /// / The proposal deadline has already passed.
    DeadlineExpired = 2,
    /// / The subgraph's network is not supported by this indexer.
    UnsupportedNetwork = 3,
    /// / The subgraph manifest could not be fetched from IPFS.
    SubgraphManifestUnavailable = 4,
    /// / The RCA names a different indexer as service provider.
    UnexpectedServiceProvider = 5,
    /// / The agreement end time has already passed.
    AgreementExpired = 6,
    /// / The agreement metadata version is not supported.
    UnsupportedMetadataVersion = 7,
    /// / The proposal's signature failed to verify.
    InvalidSignature = 8,
    /// / The signer is not an authorised agreement manager.
    SenderNotTrusted = 9,
    /// / The indexer is at its DIPs capacity; may resolve later.
    CapacityExceeded = 10,
    /// / The subgraph manifest exceeds the indexer's size cap.
    ManifestTooLarge = 11,
    /// / A re-sent proposal: an exact replay of one already rejected, or a different payload reusing an already-seen agreement id.
    ReplayDetected = 12,
    /// / The payer has insufficient escrow to back the agreement.
    InsufficientEscrow = 13,
    /// / A transient internal error; the proposal may be resent.
    IndexerUnavailable = 14,
}
impl RejectReason {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "REJECT_REASON_UNSPECIFIED",
            Self::PriceTooLow => "REJECT_REASON_PRICE_TOO_LOW",
            Self::DeadlineExpired => "REJECT_REASON_DEADLINE_EXPIRED",
            Self::UnsupportedNetwork => "REJECT_REASON_UNSUPPORTED_NETWORK",
            Self::SubgraphManifestUnavailable => {
                "REJECT_REASON_SUBGRAPH_MANIFEST_UNAVAILABLE"
            }
            Self::UnexpectedServiceProvider => {
                "REJECT_REASON_UNEXPECTED_SERVICE_PROVIDER"
            }
            Self::AgreementExpired => "REJECT_REASON_AGREEMENT_EXPIRED",
            Self::UnsupportedMetadataVersion => {
                "REJECT_REASON_UNSUPPORTED_METADATA_VERSION"
            }
            Self::InvalidSignature => "REJECT_REASON_INVALID_SIGNATURE",
            Self::SenderNotTrusted => "REJECT_REASON_SENDER_NOT_TRUSTED",
            Self::CapacityExceeded => "REJECT_REASON_CAPACITY_EXCEEDED",
            Self::ManifestTooLarge => "REJECT_REASON_MANIFEST_TOO_LARGE",
            Self::ReplayDetected => "REJECT_REASON_REPLAY_DETECTED",
            Self::InsufficientEscrow => "REJECT_REASON_INSUFFICIENT_ESCROW",
            Self::IndexerUnavailable => "REJECT_REASON_INDEXER_UNAVAILABLE",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "REJECT_REASON_UNSPECIFIED" => Some(Self::Unspecified),
            "REJECT_REASON_PRICE_TOO_LOW" => Some(Self::PriceTooLow),
            "REJECT_REASON_DEADLINE_EXPIRED" => Some(Self::DeadlineExpired),
            "REJECT_REASON_UNSUPPORTED_NETWORK" => Some(Self::UnsupportedNetwork),
            "REJECT_REASON_SUBGRAPH_MANIFEST_UNAVAILABLE" => {
                Some(Self::SubgraphManifestUnavailable)
            }
            "REJECT_REASON_UNEXPECTED_SERVICE_PROVIDER" => {
                Some(Self::UnexpectedServiceProvider)
            }
            "REJECT_REASON_AGREEMENT_EXPIRED" => Some(Self::AgreementExpired),
            "REJECT_REASON_UNSUPPORTED_METADATA_VERSION" => {
                Some(Self::UnsupportedMetadataVersion)
            }
            "REJECT_REASON_INVALID_SIGNATURE" => Some(Self::InvalidSignature),
            "REJECT_REASON_SENDER_NOT_TRUSTED" => Some(Self::SenderNotTrusted),
            "REJECT_REASON_CAPACITY_EXCEEDED" => Some(Self::CapacityExceeded),
            "REJECT_REASON_MANIFEST_TOO_LARGE" => Some(Self::ManifestTooLarge),
            "REJECT_REASON_REPLAY_DETECTED" => Some(Self::ReplayDetected),
            "REJECT_REASON_INSUFFICIENT_ESCROW" => Some(Self::InsufficientEscrow),
            "REJECT_REASON_INDEXER_UNAVAILABLE" => Some(Self::IndexerUnavailable),
            _ => None,
        }
    }
}
/// Generated client implementations.
pub mod indexer_dips_service_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    #[derive(Debug, Clone)]
    pub struct IndexerDipsServiceClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl IndexerDipsServiceClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> IndexerDipsServiceClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::Body>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> IndexerDipsServiceClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::Body>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::Body>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::Body>,
            >>::Error: Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            IndexerDipsServiceClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        /// *
        ///
        /// Propose a new *indexing agreement* to an *indexer*.
        ///
        /// The *indexer* can `ACCEPT` or `REJECT` the agreement.
        pub async fn submit_agreement_proposal(
            &mut self,
            request: impl tonic::IntoRequest<super::SubmitAgreementProposalRequest>,
        ) -> std::result::Result<
            tonic::Response<super::SubmitAgreementProposalResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/graphprotocol.indexer.dips.IndexerDipsService/SubmitAgreementProposal",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "graphprotocol.indexer.dips.IndexerDipsService",
                        "SubmitAgreementProposal",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
    }
}
/// Generated server implementations.
pub mod indexer_dips_service_server {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    /// Generated trait containing gRPC methods that should be implemented for use with IndexerDipsServiceServer.
    #[async_trait]
    pub trait IndexerDipsService: std::marker::Send + std::marker::Sync + 'static {
        /// *
        ///
        /// Propose a new *indexing agreement* to an *indexer*.
        ///
        /// The *indexer* can `ACCEPT` or `REJECT` the agreement.
        async fn submit_agreement_proposal(
            &self,
            request: tonic::Request<super::SubmitAgreementProposalRequest>,
        ) -> std::result::Result<
            tonic::Response<super::SubmitAgreementProposalResponse>,
            tonic::Status,
        >;
    }
    #[derive(Debug)]
    pub struct IndexerDipsServiceServer<T> {
        inner: Arc<T>,
        accept_compression_encodings: EnabledCompressionEncodings,
        send_compression_encodings: EnabledCompressionEncodings,
        max_decoding_message_size: Option<usize>,
        max_encoding_message_size: Option<usize>,
    }
    impl<T> IndexerDipsServiceServer<T> {
        pub fn new(inner: T) -> Self {
            Self::from_arc(Arc::new(inner))
        }
        pub fn from_arc(inner: Arc<T>) -> Self {
            Self {
                inner,
                accept_compression_encodings: Default::default(),
                send_compression_encodings: Default::default(),
                max_decoding_message_size: None,
                max_encoding_message_size: None,
            }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> InterceptedService<Self, F>
        where
            F: tonic::service::Interceptor,
        {
            InterceptedService::new(Self::new(inner), interceptor)
        }
        /// Enable decompressing requests with the given encoding.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.accept_compression_encodings.enable(encoding);
            self
        }
        /// Compress responses with the given encoding, if the client supports it.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.send_compression_encodings.enable(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.max_decoding_message_size = Some(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.max_encoding_message_size = Some(limit);
            self
        }
    }
    impl<T, B> tonic::codegen::Service<http::Request<B>> for IndexerDipsServiceServer<T>
    where
        T: IndexerDipsService,
        B: Body + std::marker::Send + 'static,
        B::Error: Into<StdError> + std::marker::Send + 'static,
    {
        type Response = http::Response<tonic::body::Body>;
        type Error = std::convert::Infallible;
        type Future = BoxFuture<Self::Response, Self::Error>;
        fn poll_ready(
            &mut self,
            _cx: &mut Context<'_>,
        ) -> Poll<std::result::Result<(), Self::Error>> {
            Poll::Ready(Ok(()))
        }
        fn call(&mut self, req: http::Request<B>) -> Self::Future {
            match req.uri().path() {
                "/graphprotocol.indexer.dips.IndexerDipsService/SubmitAgreementProposal" => {
                    #[allow(non_camel_case_types)]
                    struct SubmitAgreementProposalSvc<T: IndexerDipsService>(pub Arc<T>);
                    impl<
                        T: IndexerDipsService,
                    > tonic::server::UnaryService<super::SubmitAgreementProposalRequest>
                    for SubmitAgreementProposalSvc<T> {
                        type Response = super::SubmitAgreementProposalResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<
                                super::SubmitAgreementProposalRequest,
                            >,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as IndexerDipsService>::submit_agreement_proposal(
                                        &inner,
                                        request,
                                    )
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = SubmitAgreementProposalSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                _ => {
                    Box::pin(async move {
                        let mut response = http::Response::new(
                            tonic::body::Body::default(),
                        );
                        let headers = response.headers_mut();
                        headers
                            .insert(
                                tonic::Status::GRPC_STATUS,
                                (tonic::Code::Unimplemented as i32).into(),
                            );
                        headers
                            .insert(
                                http::header::CONTENT_TYPE,
                                tonic::metadata::GRPC_CONTENT_TYPE,
                            );
                        Ok(response)
                    })
                }
            }
        }
    }
    impl<T> Clone for IndexerDipsServiceServer<T> {
        fn clone(&self) -> Self {
            let inner = self.inner.clone();
            Self {
                inner,
                accept_compression_encodings: self.accept_compression_encodings,
                send_compression_encodings: self.send_compression_encodings,
                max_decoding_message_size: self.max_decoding_message_size,
                max_encoding_message_size: self.max_encoding_message_size,
            }
        }
    }
    /// Generated gRPC service name
    pub const SERVICE_NAME: &str = "graphprotocol.indexer.dips.IndexerDipsService";
    impl<T> tonic::server::NamedService for IndexerDipsServiceServer<T> {
        const NAME: &'static str = SERVICE_NAME;
    }
}
