// This file is @generated by prost-build.
/// *
/// A request to cancel an _indexing agreement_.
///
/// See the `DipsService.CancelAgreement` method.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CancelAgreementRequest {
    /// / The ID of the agreement to cancel.
    #[prost(bytes = "vec", tag = "1")]
    pub agreement_id: ::prost::alloc::vec::Vec<u8>,
    /// / The signature of the message.
    #[prost(bytes = "vec", tag = "99")]
    pub signature: ::prost::alloc::vec::Vec<u8>,
}
/// *
/// A response to a request to cancel an _indexing agreement_.
///
/// See the `DipsService.CancelAgreement` method.
///
/// Empty message
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct CancelAgreementResponse {}
/// *
/// A request to report the progress of an _indexing agreement_.
///
/// See the `DipsService.ReportProgress` method.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ReportProgressRequest {
    /// / The ID of the agreement to report progress for.
    #[prost(bytes = "vec", tag = "1")]
    pub agreement_id: ::prost::alloc::vec::Vec<u8>,
    /// / The signature of the message.
    #[prost(bytes = "vec", tag = "99")]
    pub signature: ::prost::alloc::vec::Vec<u8>,
}
/// *
/// A response to a request to report the progress of an _indexing agreement_.
///
/// See the `DipsService.ReportProgress` method.
///
/// TODO(LNSD): Add fields to the message
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct ReportProgressResponse {}
/// Generated client implementations.
pub mod dips_service_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    #[derive(Debug, Clone)]
    pub struct DipsServiceClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl DipsServiceClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> DipsServiceClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::BoxBody>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> DipsServiceClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::BoxBody>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
            >>::Error: Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            DipsServiceClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        /// *
        /// Cancel an _indexing agreement_.
        ///
        /// This method allows the indexer to notify the DIPs gateway that the agreement
        /// should be canceled.
        pub async fn cancel_agreement(
            &mut self,
            request: impl tonic::IntoRequest<super::CancelAgreementRequest>,
        ) -> std::result::Result<
            tonic::Response<super::CancelAgreementResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/graphprotocol.gateway.dips.DipsService/CancelAgreement",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "graphprotocol.gateway.dips.DipsService",
                        "CancelAgreement",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        /// *
        /// Report the progress of an _indexing agreement_.
        ///
        /// This method allows the indexer to report the work completed to the DIPs gateway
        /// and receive payment for the indexing work done.
        pub async fn report_progress(
            &mut self,
            request: impl tonic::IntoRequest<super::ReportProgressRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ReportProgressResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/graphprotocol.gateway.dips.DipsService/ReportProgress",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "graphprotocol.gateway.dips.DipsService",
                        "ReportProgress",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
    }
}
