//! Indexer DIPS protocol types (auto-generated).
//!
//! These types define the Dipper-to-indexer interface. The indexer-service
//! implements `IndexerDipsService` to handle:
//!
//! - `submit_agreement_proposal` - Receive and validate RCA proposals
//! - `cancel_agreement` - Unimplemented (cancellation is on-chain)

// This file is @generated by prost-build.
pub mod graphprotocol {
    pub mod indexer {
        pub mod dips {
            include!("graphprotocol.indexer.dips.rs");
        }
    }
}
