{
 "title": "TAP Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Total Pending Fees over Balance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (sender) (tap_pending_rav_grt_total) * 10^-18",
     "legendFormat": "Pending Fees {{sender}}"
    },
    {
     "expr": "tap_sender_escrow_balance_grt_total * 10^-18",
     "legendFormat": "Escrow balance {{sender}}"
    }
   ]
  },
  {
   "title": "Unaggregated fees",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "tap_unaggregated_fees_grt_total * 10^-18",
     "legendFormat": "{{sender}}-{{allocation}}"
    },
    {
     "expr": "sum by (sender) (tap_unaggregated_fees_grt_total) * 10^-18",
     "legendFormat": "Total Unaggregated Fees {{sender}}"
    },
    {
     "expr": "tap_rav_request_trigger_value * 10^-18",
     "legendFormat": "Rav Trigger {{sender}}"
    }
   ]
  },
  {
   "title": "Receipts Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(tap_receipts_received_total[$__rate_interval])",
     "legendFormat": "{{sender}}-{{allocation}}"
    }
   ]
  },
  {
   "title": "Rav Requests Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum by (sender) (rate(tap_ravs_created_total[1h]))",
     "legendFormat": "Successful Rav Requests {{sender}}"
    },
    {
     "expr": "sum by (sender) (rate(tap_ravs_failed_total[1h]))",
     "legendFormat": "Failed Rav requests {{sender}}"
    }
   ]
  },
  {
   "title": "Sender Blocked",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bool" } },
   "targets": [
    { "expr": "tap_sender_denied", "legendFormat": "{{sender}}" }
   ]
  },
  {
   "title": "Total Invalid Receipt",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "tap_invalid_receipt_fees_grt_total * 10^-18",
     "legendFormat": "{{sender}}"
    }
   ]
  }
 ]
}