name: Test TAP Protocol

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Run make setup
        run: make setup

      - name: Run make test-local
        run: make test-local

      - name: Tear down containers
        if: always()
        run: make down
