name: Test GraphTally
on:
  push:
  pull_request:
    branches: [main]

jobs:
  # test job requires a full local testnet
  # running, and it requires way more memory
  # than what actions supports
  # test:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v3
  #
  #     - name: Set up Docker Buildx # Changed from "Set up Docker" for clarity
  #       uses: docker/setup-buildx-action@v2
  #
  #     - name: Run make setup
  #       run: make setup
  #
  #     - name: Run tests
  #       run: make rav_tests
  #
  #     - name: Tear down containers
  #       if: always()
  #       run: make down
  build_docker_images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up QEMU # Useful for multi-platform builds
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx # Enhances docker build capabilities
        uses: docker/setup-buildx-action@v2

      # Login to a Docker registry is not needed if push: false and not pushing images
      # - name: Login to GitHub Container Registry
      #   uses: docker/login-action@v3
      #   with:
      #     registry: ghcr.io
      #     username: ${{ github.actor }}
      #     password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build indexer-service image with Docker Compose
        run: docker compose -f contrib/docker-compose.yml build indexer-service

      - name: Build tap-agent image with Docker Compose
        run: docker compose -f contrib/docker-compose.yml build tap-agent
