name: Test TAP Protocol

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Set up test environment
        run: |
          chmod +x setup-test-env.sh
          ./setup-test-env.sh

      - name: Run tests
        run: |
          chmod +x run-tests.sh
          ./run-tests.sh

      - name: Collect logs on failure
        if: failure()
        run: |
          docker logs indexer-service > indexer-service.log
          docker logs tap-agent > tap-agent.log
          docker logs test-runner > test-runner.log
          
      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: service-logs
          path: |
            *.log
